
language: node_js
node_js:
    - 13

services:
    - docker

# safelist
branches:
  only:
  - master

install:
    - echo "nothing needs to be installed"

before_scripts:
    - echo "no tests"

script:
    - docker --version
    - docker build -t udagram-frontend .
    - docker tag udagram-frontend sachinsharma1001/udagram-frontend:latest

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push sachinsharma1001/udagram-frontend